# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coronavirus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coronavirus.proto',
  package='coronavirus',
  syntax='proto3',
  serialized_options=b'Z\r.;coronavirus',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63oronavirus.proto\x12\x0b\x63oronavirus\"\x1e\n\x07Request\x12\x13\n\x0b\x64\x61toscorona\x18\x01 \x01(\t\"\x1d\n\x05Reply\x12\x14\n\x0c\x63onfirmacion\x18\x01 \x01(\t2G\n\x10\x44\x61tosCoronarirus\x12\x33\n\x05\x44\x61tos\x12\x14.coronavirus.Request\x1a\x12.coronavirus.Reply\"\x00\x42\x0fZ\r.;coronavirusb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='coronavirus.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datoscorona', full_name='coronavirus.Request.datoscorona', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=64,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='coronavirus.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirmacion', full_name='coronavirus.Reply.confirmacion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'coronavirus_pb2'
  # @@protoc_insertion_point(class_scope:coronavirus.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'coronavirus_pb2'
  # @@protoc_insertion_point(class_scope:coronavirus.Reply)
  })
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_DATOSCORONARIRUS = _descriptor.ServiceDescriptor(
  name='DatosCoronarirus',
  full_name='coronavirus.DatosCoronarirus',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='Datos',
    full_name='coronavirus.DatosCoronarirus.Datos',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATOSCORONARIRUS)

DESCRIPTOR.services_by_name['DatosCoronarirus'] = _DATOSCORONARIRUS

# @@protoc_insertion_point(module_scope)
