// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/coronavirus.proto

package coronavirus

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Es cliente manda los datos.
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datoscorona string `protobuf:"bytes,1,opt,name=datoscorona,proto3" json:"datoscorona,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coronavirus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coronavirus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_coronavirus_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetDatoscorona() string {
	if x != nil {
		return x.Datoscorona
	}
	return ""
}

// The response message containing the greetings
type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirmacion string `protobuf:"bytes,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coronavirus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coronavirus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_proto_coronavirus_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetConfirmacion() string {
	if x != nil {
		return x.Confirmacion
	}
	return ""
}

var File_proto_coronavirus_proto protoreflect.FileDescriptor

var file_proto_coronavirus_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x6f, 0x6e, 0x61, 0x76, 0x69,
	0x72, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x72, 0x6f, 0x6e,
	0x61, 0x76, 0x69, 0x72, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x6f, 0x73, 0x63, 0x6f, 0x72, 0x6f, 0x6e, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x6f, 0x73, 0x63, 0x6f, 0x72,
	0x6f, 0x6e, 0x61, 0x22, 0x2b, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e,
	0x32, 0x47, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x43, 0x6f, 0x72, 0x6f, 0x6e, 0x61, 0x72,
	0x69, 0x72, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x12, 0x14, 0x2e,
	0x63, 0x6f, 0x72, 0x6f, 0x6e, 0x61, 0x76, 0x69, 0x72, 0x75, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x6f, 0x6e, 0x61, 0x76, 0x69, 0x72, 0x75,
	0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x63,
	0x6f, 0x72, 0x6f, 0x6e, 0x61, 0x76, 0x69, 0x72, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_coronavirus_proto_rawDescOnce sync.Once
	file_proto_coronavirus_proto_rawDescData = file_proto_coronavirus_proto_rawDesc
)

func file_proto_coronavirus_proto_rawDescGZIP() []byte {
	file_proto_coronavirus_proto_rawDescOnce.Do(func() {
		file_proto_coronavirus_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_coronavirus_proto_rawDescData)
	})
	return file_proto_coronavirus_proto_rawDescData
}

var file_proto_coronavirus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_coronavirus_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: coronavirus.Request
	(*Reply)(nil),   // 1: coronavirus.Reply
}
var file_proto_coronavirus_proto_depIdxs = []int32{
	0, // 0: coronavirus.DatosCoronarirus.Datos:input_type -> coronavirus.Request
	1, // 1: coronavirus.DatosCoronarirus.Datos:output_type -> coronavirus.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coronavirus_proto_init() }
func file_proto_coronavirus_proto_init() {
	if File_proto_coronavirus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_coronavirus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coronavirus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_coronavirus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coronavirus_proto_goTypes,
		DependencyIndexes: file_proto_coronavirus_proto_depIdxs,
		MessageInfos:      file_proto_coronavirus_proto_msgTypes,
	}.Build()
	File_proto_coronavirus_proto = out.File
	file_proto_coronavirus_proto_rawDesc = nil
	file_proto_coronavirus_proto_goTypes = nil
	file_proto_coronavirus_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DatosCoronarirusClient is the client API for DatosCoronarirus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatosCoronarirusClient interface {
	// Sends a greeting
	Datos(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type datosCoronarirusClient struct {
	cc grpc.ClientConnInterface
}

func NewDatosCoronarirusClient(cc grpc.ClientConnInterface) DatosCoronarirusClient {
	return &datosCoronarirusClient{cc}
}

func (c *datosCoronarirusClient) Datos(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/coronavirus.DatosCoronarirus/Datos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatosCoronarirusServer is the server API for DatosCoronarirus service.
type DatosCoronarirusServer interface {
	// Sends a greeting
	Datos(context.Context, *Request) (*Reply, error)
}

// UnimplementedDatosCoronarirusServer can be embedded to have forward compatible implementations.
type UnimplementedDatosCoronarirusServer struct {
}

func (*UnimplementedDatosCoronarirusServer) Datos(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Datos not implemented")
}

func RegisterDatosCoronarirusServer(s *grpc.Server, srv DatosCoronarirusServer) {
	s.RegisterService(&_DatosCoronarirus_serviceDesc, srv)
}

func _DatosCoronarirus_Datos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatosCoronarirusServer).Datos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coronavirus.DatosCoronarirus/Datos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatosCoronarirusServer).Datos(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatosCoronarirus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coronavirus.DatosCoronarirus",
	HandlerType: (*DatosCoronarirusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Datos",
			Handler:    _DatosCoronarirus_Datos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coronavirus.proto",
}
